export const SET_STATE = `SET_STATE`;
export const DELETE = `DELETE`;

/* POSTS */

export const REQUEST_POSTS = `REQUEST_POSTS`;
export const REQUEST_POSTS_SUCCESS = `REQUEST_POSTS_SUCCESS`;
export const REQUEST_POSTS_ERROR = `REQUEST_POSTS_ERROR`;

export const CREATE_POSTS = `CREATE_POSTS`;
export const CREATE_POSTS_SUCCESS = `CREATE_POSTS_SUCCESS`;
export const CREATE_POSTS_ERROR = `CREATE_POSTS_FAILED`;
 

/* UTILS */

export const SWITCH_VISIBILITY = `SWITCH_VISIBILITY`;
export const HANDLE_SUBMIT = `HANDLE_SUBMIT`;
export const MESSAGES = `MESSAGES`;

