export const SET_STATE = `SET_STATE`;
export const DELETE = `DELETE`;

/* POSTS */

export const REQUEST_POSTS = `REQUEST_POSTS`;
export const REQUEST_POSTS_SUCCESS = `REQUEST_POSTS_SUCCESS`;
export const REQUEST_POSTS_FAILED = `REQUEST_POSTS_FAILED`;

export const CREATE_POSTS = `CREATE_POSTS`;
export const CREATE_POSTS_SUCCESS = `CREATE_POSTS_SUCCESS`;
export const CREATE_POSTS_FAILED = `CREATE_POSTS_FAILED`;

export const DELETE_POSTS = `DELETE_POSTS`;
export const DELETE_POSTS_SUCCESS = `DELETE_POSTS_SUCCESS`
export const DELETE_POSTS_FAILED = `DELETE_POSTS_FAILED`

export const UPDATE_POSTS = `UPDATE_POSTS`;
export const UPDATE_POSTS_SUCCESS = `UPDATE_POSTS_SUCCESS`;
export const UPDATE_POSTS_FAILED = `UPDATE_POSTS_FAILED`;


 

/* UTILS */

export const SWITCH_VISIBILITY = `SWITCH_VISIBILITY`;
export const HANDLE_SUBMIT = `HANDLE_SUBMIT`;
export const MESSAGES = `MESSAGES`;
export const HANDLE_POST_CHANGE = `HANDLE_POST_CHANGE`;

